### ISSUE TITLE
Compiling to wasm is broken because of upstream dependency of Instant

### ISSUE THREAD

**Issue by purung** [bladecoder/blade-ink-rs#14]
Instant depends on stdweb, which breaks with newer versions of wasm-bindgen. The Instant crate is no longer maintained and suggests using web-time instead. I don't know yet if that is complicated to do.

**Comment by bladecoder** [comment]
Replaced the `Instant` crate with `web-time` in v1.1.0.

I didn't test it for wasm, so let me know if it works well.
