### ISSUE TITLE
`LIST_ALL` returns wrong result for combinations of multiple lists

### ISSUE THREAD

**Issue by IFcoltransG** [bladecoder/blade-ink-rs#4]
```ink
LIST a = A
LIST b = B
{LIST_ALL(A + B)}
```
Inky output (expected): `A, B`
Blade Ink Rs output: `B`

I haven't checked whether this affects the Java version too. I don't see a test for this in [Ink Proof](https://github.com/chromy/ink-proof), so I don't think integrating with it would have caught it.

JSON:
```json
{"inkVersion":21,"root":[["ev",{"VAR?":"A"},{"VAR?":"B"},"+","LIST_ALL","out","/ev","\n",["done",{"#f":5,"#n":"g-0"}],null],"done",{"global decl":["ev",{"list":{},"origins":["a"]},{"VAR=":"a"},{"list":{},"origins":["b"]},{"VAR=":"b"},"/ev","end",null],"#f":1}],"listDefs":{"a":{"A":1},"b":{"B":1}}}
```

It seems like it's a problem with the `&params[0]` only getting one list item in [`NativeFunctionCall::all_op`](https://github.com/bladecoder/blade-ink-rs/blob/eac5b1da3a4d8ea934082047ccfce972f25481ae/lib/src/native_function_call.rs#L930C15-L930C31) in `native_function_call`.

**Comment by bladecoder** [comment]
Fixed. The Java version was correct.

Thanks!
