### ISSUE TITLE
Shuffle always produces same result

### ISSUE THREAD

**Issue by IFcoltransG** [bladecoder/blade-ink-rs#9]
```ink
-> main
=== main
{~1|2|3|4|5|6|7|8|9|10}
+ [Continue]
-> main
```
I expect this to produce each number exactly once, in a random order, then restart and produce each number again exactly once, in a random order. Instead, I get the same number over and over again.

Expected:
```
3
1
9
...
```
Actual:
```
6
6
6
...
```

**Comment by bladecoder** [comment]
Fixed in release v1.0.1
